### ISSUE TITLE
How to signout?

### ISSUE THREAD

**Issue by uuuueuphoria** [johnmason27/basic-auth#1]
Hi John,

I saw your tutorial and it is really helpful. However, I read so many documentation and did not figure out how to sign out from office365. Can you give me some advice?

Thanks

**Comment by johnmason27** [comment]
I'll look at this tomorrow

**Comment by uuuueuphoria** [comment]
> I'll look at this tomorrow @uuuueuphoria

Sounds good! Thanks a lot

**Comment by johnmason27** [comment]
Not 100% sure myself after a quick look. Might want to look at the `httpContext.SignOutAsync()` method. I think you could do something with that. You may have to add an extra url in your appsettings.json which is your sign out url.

**Comment by uuuueuphoria** [comment]
I created a logout controller with this.httpcontext.SignOutAsync method yesterday and nothing happened. I also tried with link /signout-oidc and no luck. Do you know if I need to add anything in the startup file? I will try to add signout url in app settings.json

**Comment by johnmason27** [comment]
Yeah I think there might be something you need to setup in the Startup.cs

Don't know whether anything here could help? 
https://joonasw.net/view/aad-single-sign-out-in-asp-net-core

I think you may need something in the startup but I'm not sure myself.
